In [3]:
import numpy as np


a = np.arange(15).reshape(3, 5)
print(a)
a.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


(3, 5)

In [21]:
print("Nbr of dimensions: "+str(a.ndim))

print("Type of the elements in the array: "+str(a.dtype.name))


print("The buffer containing the actual elements of the array: ")
print(a.data)

print("Size in bytes of each element of the array: "+str(a.itemsize))

print("The total number of elements of the array: "+str(a.size))

print("Dimensions of the array: "+str(a.shape))


Nbr of dimensions: 2
Type of the elements in the array: int32
The buffer containing the actual elements of the array: 
Size in bytes of each element of the array: 4
The total number of elements of the array: 15
Dimensions of the array: (3, 5)


In [22]:
type(a)

numpy.ndarray

In [24]:
#Creating arrays

a = np.array([2,3,4])
b = np.array([1.2, 3.5, 5.1])

print(a.dtype)
print(b.dtype)


int32
float64


In [28]:
#More dimensions
c = np.array([(1.5,2,3), (4,5,6)])
print(c)
print(c.shape)

[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]
(2, 3)


In [29]:
#Type of array can be explicitely specified
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c


array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [31]:
#Creating placeholder arrays
#Zeros
np.zeros((3,4))


array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [34]:
#Ones
np.ones((2,3,4), dtype=np.int16)


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [36]:
#Fill with random values
np.empty((2,3))  

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [37]:
#Creating array with a sequence of numbers
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [38]:
#We can also define how many elements we want instead of the range
np.linspace( 0, 2, 9 ) 

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [39]:
#Element-wise operations:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [40]:
a-b


array([20, 29, 38, 47])

In [41]:
b**2

array([0, 1, 4, 9])

In [42]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [43]:
a<35

array([ True,  True, False, False], dtype=bool)

In [44]:
#Matrix operations:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])


In [45]:
A*B

array([[2, 0],
       [0, 4]])

In [47]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [48]:
#Modify existing arrays:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))


In [49]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [50]:
b += a
b

array([[ 3.0640486 ,  3.97270802,  3.13581398],
       [ 3.18092749,  3.93979118,  3.51348187]])

In [51]:
#Unary operations:
a = np.random.random((2,3))
a

array([[ 0.83384035,  0.40949739,  0.75334093],
       [ 0.01041037,  0.03782057,  0.97177582]])

In [53]:
a.sum()

3.0166854357884381

In [55]:
a.min()

0.010410367259217734

In [56]:
a.max()

0.97177581611582498

In [57]:
#Taking into account the dimensions of an array:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
#Column-wise sum
b.sum(axis=0)

array([12, 15, 18, 21])

In [59]:
#Row-wise min
b.min(axis=1)

array([0, 4, 8])

In [60]:
#Row-wise cumulative sum
b.cumsum(axis=1) 

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [61]:
#Universal functions:
B = np.arange(3)
np.exp(B)
np.sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [62]:
#Indexing:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [66]:
print(a[2])
print(a[2:5])

# equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a[:6:2] = -1000
a

-1000
[-1000    27 -1000]


array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729], dtype=int32)

In [67]:
for i in a:
    print(i**(1/3.))


nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


D:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [68]:
#Multidimensional arrays
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
b


array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [69]:
b[2,3]

23

In [70]:
b[0:5,1]  

array([ 1, 11, 21, 31, 41])

In [71]:
b[:,1] 

array([ 1, 11, 21, 31, 41])